-- MySQL Script generated by MySQL Workbench
-- Wed Mar  5 15:37:05 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `consulta médica` DEFAULT CHARACTER SET utf8 ;
USE `consulta médica` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consulta médica`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `id_tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `id_tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consulta médica`.`tipo_usuario` (
  `idtipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo_usuario` VARCHAR(45) NOT NULL,
  `descripcion_tipo_usuario` VARCHAR(45) NOT NULL,
  `created` VARCHAR(45) NOT NULL,
  `updated` DATETIME NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idtipo_usuario`),  -- This column will be the primary key
  INDEX `fk_tipo_usuario_usuario1_idx` (`idusuario` ASC, `idtipo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_usuario_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `mydb`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consulta médica`.`Paciente` (
  `idPaciente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATETIME NOT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `idusuario` INT NOT NULL,
  `id_tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`idPaciente`, `idusuario`, `id_tipo_usuario`),
  INDEX `fk_Paciente_usuario1_idx` (`idusuario` ASC, `id_tipo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Paciente_usuario1`
    FOREIGN KEY (`idusuario` , `id_tipo_usuario`)
    REFERENCES `mydb`.`usuario` (`idusuario` , `id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consulta médica`.`citas` (
  `idcitas` INT NOT NULL AUTO_INCREMENT,
  `fecha_cita` DATETIME NOT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `idPaciente` INT NOT NULL,
  PRIMARY KEY (`idcitas`, `idPaciente`),
  INDEX `fk_citas_Paciente1_idx` (`idPaciente` ASC) VISIBLE,
  CONSTRAINT `fk_citas_Paciente1`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `mydb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`areas_especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consulta médica`.`areas_especialidad` (
  `idareas_especialidad` INT NOT NULL AUTO_INCREMENT,
  `nombre_sala` VARCHAR(45) NOT NULL,
  `descripcion_sala` VARCHAR(45) NOT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  PRIMARY KEY (`idareas_especialidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consulta médica`.`doctor` (
  `iddoctor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `idusuario` INT NOT NULL,
  `id_tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`iddoctor`, `idusuario`, `id_tipo_usuario`),
  INDEX `fk_doctor_usuario1_idx` (`idusuario` ASC, `id_tipo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_doctor_usuario1`
    FOREIGN KEY (`idusuario` , `id_tipo_usuario`)
    REFERENCES `mydb`.`usuario` (`idusuario` , `id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seguros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consulta médica`.`seguros` (
  `idseguros` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `decripcion` VARCHAR(45) NOT NULL,
  `created` VARCHAR(45) NOT NULL,
  `updated` VARCHAR(45) NOT NULL,
  `idPaciente` INT NOT NULL,
  PRIMARY KEY (`idseguros`, `idPaciente`),
  INDEX `fk_seguros_Paciente1_idx` (`idPaciente` ASC) VISIBLE,
  CONSTRAINT `fk_seguros_Paciente1`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `mydb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tratamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consulta médica`.`tratamiento` (
  `idtratamiento` INT NOT NULL AUTO_INCREMENT,
  `nombre_tratamiento` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `idPaciente` INT NOT NULL,
  PRIMARY KEY (`idtratamiento`, `idPaciente`),
  INDEX `fk_tratamiento_Paciente1_idx` (`idPaciente` ASC) VISIBLE,
  CONSTRAINT `fk_tratamiento_Paciente1`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `mydb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doctor_has_areas_especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consulta médica`.`doctor_has_areas_especialidad` (
  `doctor_iddoctor` INT NOT NULL,
  `areas_especialidad_idareas_especialidad` INT NOT NULL,
  PRIMARY KEY (`doctor_iddoctor`, `areas_especialidad_idareas_especialidad`),
  INDEX `fk_doctor_has_areas_especialidad_areas_especialidad1_idx` (`areas_especialidad_idareas_especialidad` ASC) VISIBLE,
  INDEX `fk_doctor_has_areas_especialidad_doctor1_idx` (`doctor_iddoctor` ASC) VISIBLE,
  CONSTRAINT `fk_doctor_has_areas_especialidad_doctor1`
    FOREIGN KEY (`doctor_iddoctor`)
    REFERENCES `mydb`.`doctor` (`iddoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doctor_has_areas_especialidad_areas_especialidad1`
    FOREIGN KEY (`areas_especialidad_idareas_especialidad`)
    REFERENCES `mydb`.`areas_especialidad` (`idareas_especialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
